import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {  
  //const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const data = api.post.getLatest.useQuery().data;

  return (
    <>
      <Head>
        <title>PROJECT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            I HATE SEA TURTLES
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <Link
              className="flex max-w-xs flex-col gap-10 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/edits/landing"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Landing page →</h3>
              <div className="text-lg">
                welcome!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-10 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/edits/landing"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Beaches →</h3>
              <div className="text-lg">
                {data?.map(({id, content}) => (<div key={id}>{content}</div>))}
              </div>
            </Link>
            <div className="overflow-x-auto relative h-screen font-mhs text-white">
              <table className="wfull border">
                <thead className="text-left">
                  <tr className="border-b-2">
                    <th className='w-2/12' scope="col">Location</th>
                    <th className='w-1/12' scope="col">Content</th>
                  </tr>
                </thead>
                <tbody className=" ">
                  {data?.map(({email, content}) => (
                    <tr key={email} className="border-b-2">
                      {/* ID */}
                      <td className="w-2/12">
                        {email}
                      </td>
                      <td className="w2/12">
                        {content}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              </div>
          </div>
        </div>
      </main>
    </>
  );
  
  }

